let car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car != 'subaru'? I predict false.");
console.log(car != 'subaru');
car = "Honda";
console.log("is car == 'subaru'? I predict false.");
console.log(car == 'subaru');
console.log("is car != 'subaru'? I predict true.");
console.log(car != 'subaru');
console.log("is car == 'Honda'? I predict true.");
console.log(car == 'Honda');
car = "Hundai";
console.log("is car != 'Hundai'? I predict true.");
console.log(car != 'Hundai');
let passNumber = 40;
console.log("is passNumber > 35 ? I predict true.");
console.log(passNumber > 35);
console.log("is passNumber < 35 ? I predict false.");
console.log(passNumber < 35);
console.log("is passNumber <= 39 ? I predict false.");
console.log(passNumber <= 39);
console.log("is passNumber <= 40 ? I predict true.");
console.log(passNumber <= 40);
export {};
